# flux HelmChart CRD to gran nginx ingress contoller chart

apiVersion: helm.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart:
    spec:
      chart: nginx-ingress
      version: 1.3.x
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: nginx
  releaseName: nginx
  targetNamespace: nginx
  interval: 1h
