# flux HelmRelease crd for installing nginx ingress controller

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  timeout: 10m
  chart:
    spec:
      chart: nginx-ingress
      version: 1.3.x
      interval: 5h
      sourceRef:
        kind: HelmRepository
        name: nginx
  releaseName: nginx
  targetNamespace: nginx
  interval: 1h
