# flux HelmChart CRD to gran nginx ingress contoller chart

apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  chart: nginx-ingress
  version: 1.2.x
  interval: 5h
  sourceRef:
    kind: HelmRepository
    name: nginx
    targetNamespace: nginx
    releaseName: nginx
    interval: 1h
