# flux HelmRepository for installing nginx ingress controller

apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 1h
  url: oci://ghcr.io/nginx/charts
  type: oci
